### ISSUE TITLE
[Discussion] 9anime Adblock detection message

### ISSUE THREAD

**Issue by dexatq** [lap00zza/9anime-Companion#101]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Turning off **Remove ads** will still give the message "Please turn off adblock".
I found out that the cause is if you have **Remove social share** enabled.

Turning off both **Remove ads** and **Remove social share** will show ads and won't trigger the "Please turn off adblock" message.

**Comment by lap00zza** [comment]
@dexatq thanks for reporting, also thanks for the heads up 😄 . I was thinking the issue was because I inject the code to disable adblock detection only when remove ads is on.

**Comment by lap00zza** [comment]
@dexatq try the build from here: https://ci.appveyor.com/project/lap00zza/9anime-companion/build/1.4.0.13/artifacts and let me know if its working as expected.

Install instructions: https://github.com/lap00zza/9anime-Companion/wiki/Running-in-Developement-Mode

**Comment by dexatq** [comment]
@lap00zza Seems to be working.

**Comment by lap00zza** [comment]
For future readers, this issue was created for this reddit thread: https://www.reddit.com/r/9anime/comments/7eu6mt/strange/

> Strange self.9anime
Submitted an hour ago by dexatq
It's interesting that somehow I actually cannot turn off adblock on 9anime. Its so strange that when I turn off ublock origin and the remove ad one in 9anime companion I get the message please turn off adblock. I turn them both on and I bypass the message. Something really strange is going on with the detection thing.

**Comment by SheepKid12** [comment]
@lap00zza Using chrome and the build linked above, I am seeing the disable adblock message still. Chrome does say that it is loaded from where I extracted it.

I have also found out that enabling the "Ignore generic cosmetic filters" option in ublock, I don't see the disable adblock message at all.

**Comment by CaelThunderwing** [comment]
wow they were fast, they just blocked this update :/  wonder now if they're breaking it apart via source  :/

**Comment by SimonMattila** [comment]
![image](https://user-images.githubusercontent.com/10836780/33158028-c47fd9ae-d006-11e7-8253-d2c57c8322cd.png)
![image](https://user-images.githubusercontent.com/10836780/33158036-cf86f242-d006-11e7-8080-7231e8189e1d.png)
![image](https://user-images.githubusercontent.com/10836780/33158041-dbccc37e-d006-11e7-9711-73a74da3703a.png)

9anime official reddit replies

**Comment by CaelThunderwing** [comment]
they admin seems intent to Potentially look at IPBaning Users of the plugin now.  (sorry i dont know how to embedd Images in github Comments.)
https://i.imgur.com/hufOWGD.png

**Comment by SheepKid12** [comment]
@CaelThunderwing that was from /u/9animecrit, apparently the actual 9anime is /u/9anime on Reddit, but I’m not sure.

**Comment by CaelThunderwing** [comment]
@SheepKid12 same broken language and near same Response times. there isnt one sole Admin of the site i'm Sure.

**Comment by SheepKid12** [comment]
@CaelThunderwing like I said, I don’t know what account is official or not. 

Either way, I feel like 9anime is going to crap, so I’m going elsewhere to watch anime.

**Comment by CaelThunderwing** [comment]
@SheepKid12 yea i just went back to KissAnime unf feel so dirty..  but lul the staff wiped all thier responses to Anything ad related or suggestions (looks like they've abandoned the subredit.)

**Comment by lap00zza** [comment]
Guys checkout the patched build: https://ci.appveyor.com/project/lap00zza/9anime-companion/branch/master

@CaelThunderwing @SheepKid12 @SimonMattila (refer to wiki for how to install in dev mode)

**Comment by yumiris** [comment]
@lap00zza, I tested out the latest artifacts; all seems to be working. [Here's a somewhat fancy report](https://github.com/lap00zza/9anime-Companion/files/1498664/9anime.Companion.-.Ad.Block.Test.pdf) if needed 😜

**Comment by CaelThunderwing** [comment]
@lap00zza working in Chrome, (i made a regret using FF Dev v58 Soooo many sites were forcing HTTPS and breaking them in the process,) lets see how long this lasts.

**Comment by lap00zza** [comment]
This time I have added a way to remotely patch it 😄 . People wont need to update it from CWS/AMO, just `Settings > Anti Adblock Detection > Update`

**Comment by CaelThunderwing** [comment]
i got IPBanned once was a matter of getting my AIO Gateway to pull a new IP :D (Swappe dto bridge mode used a router and blam. new IP and moved it back into AIO mode.)

**Comment by lap00zza** [comment]
This issue is fixed in release [1.3.2](https://github.com/lap00zza/9anime-Companion/releases/tag/1.3.2). I published the changes to Chrome Web Store and Addons.Mozilla.Org just now. Changes should be live within the next 1 hour. *Don't forget to update.*

**Comment by LordDamionDevil** [comment]
To be fair after updating the anti adblock detection it still gives me the message Please disable AdBlock then refresh this page and try again.
Don't use any 3rd extension to remove anything on this page.

**Comment by lap00zza** [comment]
@LordDamionDevil yes it looks like they changed the detection code again :woman_facepalming:

**Comment by lap00zza** [comment]
Reverted most of the changes from the previous release in `1.3.3` because it was not a very reliable way to deal with the anti adblock (I still haven't found a way), also the Github permission was a bit worrisome. For the time being if you see a please disable adblock message, goto 9anime Companion Settings > disable `Remove Ads` and `Remove Social Share`.

**Comment by CaelThunderwing** [comment]
yea w/ as fast they keep updating, someone's stalking the repo.

**Comment by sliperhr** [comment]
so its they a way to disable the ads without getting the turn of the adblock text?

**Comment by lap00zza** [comment]
@sliperhr at the moment no. Will take a little bit of time.

**Comment by SheepKid12** [comment]
@lap00zza @sliperhr Even if a way around the adblocking is found, 9anime will probably patch it again. Even then, what’s stopping them from blocking the entire extension?

**Comment by Dibakarroy1997** [comment]
**## Download all section got autohide.**

First of all sorry that I created separate issue for this one. Didn't realize that it has to do something with adblock feature.


Here is the screenshot of the problem I am facing. For an instance when the page is still loading I can see all the server list but vanishes when the page is fully loaded. 

![screenshot from 2017-11-24 22-27-12](https://user-images.githubusercontent.com/17507690/33219556-db357d4e-d168-11e7-9c55-541c8e99d7de.png)

Noticed that if I disable the adblock feature then, the section hiding problem is not there anymore.

**Comment by lap00zza** [comment]
Looks like they don't want people to be able to download as well when `Remove Ads` is enabled 😢 They keep changing the adblock detection process as well.

**Comment by Dibakarroy1997** [comment]
Also noticed that even if I don't use companion adblock but in place use uBlock Origin to block ads, then also it auto hide the server section on page load.

**Comment by RabidWolf** [comment]
It seems to be uBlock that hides the servers however it wouldn't surprise me if they did stop people downloading episodes, It's what I'm doing.

**Comment by youriyep** [comment]
![image](https://user-images.githubusercontent.com/29116570/33219915-4f3aee64-d145-11e7-807f-a41e656b8e4b.png) If you're fast enough you can still download episodes

**Comment by CaelThunderwing** [comment]
![download links](https://user-images.githubusercontent.com/3792137/33220139-083c0538-d114-11e7-8af9-84541447ee72.png)

i'm able to see the link for downloading and Server list.

**Comment by CaelThunderwing** [comment]
They've Just blocked Downloading. atleast thru the plugin.

**Comment by josiec09** [comment]
To tell you the truth i pretty much just moved on from 9anime i am fine with seeing ads but not when they are trying to install shit to my pc and when every blank space on the site is filled with them. I would be a little more willing to deal with that many ads if the you know they hosted the video files them self.

**Comment by CaelThunderwing** [comment]
looks like they gave up and Enabled Adblockers tested w/ just UBlock, and got no Message,

**Comment by Wyn10** [comment]
@CaelThunderwing Looks like they removed any reference of blocking adblockers on there twitter as well.

**Comment by sliperhr** [comment]
is is just me or 9anime keep refreshing automatically?

**Comment by Wyn10** [comment]
Yeah only when logged into 9anime, issue not on our end @sliperhr

**Comment by Dibakarroy1997** [comment]
Did everything revert back just now? Cause companion adblock is working and there is no auto hide anymore. Everything seems alright now.

**Comment by lap00zza** [comment]
everything except downloading: #106

**Comment by sliperhr** [comment]
yes only when logged in @Wyn10
