### ISSUE TITLE
9anime detects companion

### ISSUE THREAD

**Issue by vollrum** [lap00zza/9anime-Companion#102]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
It seems as though 9anime detects 9anime companion because it shows the message "Please disable AdBlock then refresh this page and try again. Don't use any 3rd extension to remove anything on this page."

Screenshot: https://i.imgur.com/furuKqI.png

**Comment by lap00zza** [comment]
lets continue this discussion in #101
