### ISSUE TITLE
Extension new permission: read and change your data on github.com

### ISSUE THREAD

**Issue by Ahmad-Magdy-Osman** [lap00zza/9anime-Companion#104]
**Select your issue type:** (check at least one)
- [x] Bug
- [x ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
What is the reason for requiring such permission?

**Comment by lap00zza** [comment]
Cross origin permission to get remote patches to disable adblock detection
https://github.com/lap00zza/9anime-Companion/blob/82879507bf6246846552f08052a05e6d134b32f1/src/dashboard.ts#L331-L341

**Comment by lap00zza** [comment]
I tried without having to resort to the permission but wasnt able to find a solution. If I find one I will remove that perm. If you have any idea please do share.

**Comment by Ahmad-Magdy-Osman** [comment]
Why not use pastebin.com instead of Github? Github's access is worrisome.

**Comment by lap00zza** [comment]
So that I can keep all the related code together. But yes I otherwise agree, I should probably remove the github permission.

**Comment by Ahmad-Magdy-Osman** [comment]
I understand the code being together part. You can even have a small python script to update the pastebin from the repository json file.
