### ISSUE TITLE
Download Not working

### ISSUE THREAD

**Issue by ZekromInfinity** [lap00zza/9anime-Companion#108]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
The download button is there to use but the downloads won't initiate. Maybe the site has done some counteraction to prevent 9anime companion from working. I tried removing and reinstalling 9anime companion to make sure but the issue continues. 

Thank You

**Comment by lap00zza** [comment]
Hi please check #106

**Comment by CaelThunderwing** [comment]
@lap00zza i can confirm the fix has been blocked again so soon. tested teh artifact in FFv57 (by loading temporary plugin only way it'll load unsigned plugins) and Chrome.

**Comment by lap00zza** [comment]
fixed in #106 . RapidVideo discussion: #109
