### ISSUE TITLE
[META]: Get RapidVideo download to work

### ISSUE THREAD

**Issue by lap00zza** [lap00zza/9anime-Companion#109]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

**Comment by hoppler** [comment]
target has same encryption as token and options. either rot8 or the newer one. remeber: every value starting with an odd value like . or - is encrypted by either rot8 or the token encryption
