### ISSUE TITLE
Ads are appearing again 

### ISSUE THREAD

**Issue by sliperhr** [lap00zza/9anime-Companion#116]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
ads are coming back ,hope you guys can fix this, :)

![screenshot_3](https://user-images.githubusercontent.com/33209981/34054895-ca26e57e-e207-11e7-8fd1-ed915db1a6d0.jpg)

**Comment by densityx** [comment]
duplicate #115
