### ISSUE TITLE
Downloads Failing From Rapid Video after Installing 1.4.0.29

### ISSUE THREAD

**Issue by Power27** [lap00zza/9anime-Companion#119]
**Select your issue type:** (check at least one)
- [X] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

When trying to download Episodes through Rapid Video only some will work and others will fail as below;

![image](https://user-images.githubusercontent.com/34653070/34114649-3d033da4-e40b-11e7-9189-a4e456207c3c.png)

I have tried External and Browser through Firefox and Google Chrome.
One of the affected series is:- https://9anime.is/watch/91-days-dub.xoyw/vqp086 

Please advise if you need further information. 

Thanks.

---
EDITED BY @lap00zza
1.4.0.29 refers to the artifacts here: https://ci.appveyor.com/project/lap00zza/9anime-companion/build/1.4.0.29/artifacts

**Comment by Power27** [comment]
Just to add it seems no downloads are working again.

**Comment by ootagoo** [comment]
Same issue here

**Comment by Power27** [comment]
Tried again this morning and some are working again, just seems to be very hit and miss

**Comment by lap00zza** [comment]
Hi I tried download from the above link. The episodes I tried seemed to work:

![image](https://user-images.githubusercontent.com/8621583/34155128-27f5e67c-e4de-11e7-815a-b854f54abc7b.png)

**Comment by lap00zza** [comment]
@Power27 @ootagoo if you guys get failed downloads again just try one thing. Try playing that episode on 9anime. What happens sometime have broken videos (removed etc).

**Comment by zrattz** [comment]
All works fine for me. It wont change to lower video quality if you download 1080 and there isnt any its just skips it

**Comment by lap00zza** [comment]
@zrattz unfortunately that behaviour cant be changed (I dont know a good way to fix it). Reason:

>RapidVideo is a bit sly in this regard. The don't give the URL's for all the qualities on a single video page. Each quality is associated with a different video page. So 9anime Companion cant automatically select the next lower quality because that would require parsing 4 pages for just 1 video.

from: https://github.com/lap00zza/9anime-Companion/commit/ae7229e8d0ea9c031b6d92d071454407956f03dc#commitcomment-26343859

**Comment by zrattz** [comment]
I know:/

**Comment by antony-jr** [comment]
giving the ```q=<VIDEO_QUALITY>``` parameter to the **RapidVideo** target link will automatically redirect to the specific page. 
If the specific quality is not given in RapidVideo then there will be no ```<video>``` tags in the response.

# Example
```
https://www.rapidvideo.com/e/FK59KA2G1W&q=480p
```

**Comment by Power27** [comment]
They are still failing for me, even though the video plays;

![image](https://user-images.githubusercontent.com/34653070/34207205-63577c8c-e581-11e7-9377-c096338aef8f.png)

**Comment by zrattz** [comment]
IS the download set to 720p?

**Comment by zrattz** [comment]
IS the download set to 720p?

**Comment by Power27** [comment]
Yes

**Comment by Power27** [comment]
![image](https://user-images.githubusercontent.com/34653070/34208356-167e7e88-e586-11e7-8780-4beeb0d8edbe.png)

**Comment by zrattz** [comment]
Do you have latest build`?
https://ci.appveyor.com/project/lap00zza/9anime-companion/build/artifacts

**Comment by Power27** [comment]
I believe so, not sure if i have installed it correctly though.

![image](https://user-images.githubusercontent.com/34653070/34208586-e40c5316-e586-11e7-919c-38436cbb2fa0.png)

**Comment by zrattz** [comment]
Looks like its the right one. i tested Firefix one aswell and that one works aswell for me
Try delete extention and install again

**Comment by zrattz** [comment]
And rapid only works in browser aswell i think

**Comment by Power27** [comment]
I just tried it again and S1 is working. Maybe its something to do with my Internet as its very hit and miss

**Comment by salehanime** [comment]
i update the last version and its `work`
but the name of episode like this ((360FKMFVKXJEFB5IZWB57))
please help

**Comment by zrattz** [comment]
Need to use browser

**Comment by salehanime** [comment]
download from browser doesnot work for me 
when i choose browser download show like this  ((Status: ✔ Completed 004)) but the episode donot download in my browser

please help

**Comment by zrattz** [comment]
got latest build 1.4.0.29?

**Comment by zrattz** [comment]
I downloaded Entire naruto today with some faled 4 of 220

**Comment by salehanime** [comment]
i install last version 1.4.0.29 but  the same problem

**Comment by zrattz** [comment]
what series and episode?

**Comment by salehanime** [comment]
this anime .HACK//ROOTS

**Comment by zrattz** [comment]
same problem with me other series works tho and for hack i need to press 720p to even get it start playing i gues its a bug on 9anime's part

**Comment by antony-jr** [comment]
hmm...

**Comment by lap00zza** [comment]
@salehanime thanks for reporting. It happened to an error in the filename. fixed in 1e18fc2. Get the build artifacts here: https://ci.appveyor.com/project/lap00zza/9anime-companion/build/1.4.0.30/artifacts (once its done)

**Comment by lap00zza** [comment]
Closing this issue for now. Feel free to reopen if the need arises.

**Comment by matthewd253** [comment]
Hello Lap00zza, yeah i read everything here and now have the download button on the RapidVideo, but now i a, having the issue of all the video's fail to download. I have tried everything that was on this page for help. Nothing worked.

**Comment by lap00zza** [comment]
@matthewd253 looks like its because of file name again. Get the build artifacts from: https://ci.appveyor.com/project/lap00zza/9anime-companion/build/1.4.0.31/artifacts

Please reply and let me know if this fixed your issue.

**Comment by matthewd253** [comment]
@lap00zza It did fix the issue and it is letting me download anime once again. Thank you so much for the help! I'm so happy i can go back to downloading my anime and watching them with no issues at all!

**Comment by RazorJazz9** [comment]
@lap00zza I read all things above but the link u gave is not loading

**Comment by lap00zza** [comment]
@RazorJazz9 no worries. I am linking them here:
* https://www.dropbox.com/s/80g1ugmo9rvsfpv/9anime_Companion-firefox-1.4.0.34.xpi?dl=0
* https://www.dropbox.com/s/4zbk2gqabiubd3m/9anime_Companion-chrome-1.4.0.34.zip?dl=0

**NOTE**
For anyone else viewing this post, please refer to https://github.com/lap00zza/9anime-Companion/issues/119#issuecomment-353057933 for downloading the latest build. The dropbox links in this post might not be the latest build.

**Comment by RazorJazz9** [comment]
@lap00zza Thanks man, its working now
