### ISSUE TITLE
Download Button Not Working

### ISSUE THREAD

**Issue by RazorJazz9** [lap00zza/9anime-Companion#123]
**Select your issue type:** (check at least one)
- [x] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
The download button for the RapidVideo is not present. Also I don't see any other download button on page. Download shortcuts are also not working . What can I do?

**Comment by lap00zza** [comment]
@RazorJazz9 check https://github.com/lap00zza/9anime-Companion/issues/119#issuecomment-353057933. If your issue is still present, please reopen this issue.
