### ISSUE TITLE
Download button not visible

### ISSUE THREAD

**Issue by sharathm6** [lap00zza/9anime-Companion#126]
##### Select your issue type: (check at least one)

- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other

##### Steps to reproduce:

1. ...Installed the extension and logged on to MAL and 9 anime.
2. ...Download button not visible as it is shown in the pictures

##### Describe your issue:

Download button not visible under the server name as it is shown in the pictures. So i am not able to download videos/series from 9anime.to/is

**Comment by lap00zza** [comment]
Please refer to https://github.com/lap00zza/9anime-Companion/issues/119#issuecomment-353057933. Reopen this issue if you still cant download.
