### ISSUE TITLE
Next Update?

### ISSUE THREAD

**Issue by A-1K** [lap00zza/9anime-Companion#132]
#### Select your issue type: (check at least one)

- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other

#### Steps to reproduce:

1. 
2. 

#### Describe your issue:
MAL integration doesn't work.Also no download button. When are you going to update this extension ? Things are pretty messed up.

**Comment by densityx** [comment]
Do read the heading https://github.com/lap00zza/9anime-Companion/blob/master/README.md

**Comment by A-1K** [comment]
Yeah, sorry my bad
