### ISSUE TITLE
Suggestion : Standardised double (or triple) digit numbering for download file names

### ISSUE THREAD

**Issue by Neptuneras** [lap00zza/9anime-Companion#14]
On many devices and some in-home players, how they sort the files would be by filename, so for an 100 episode show, it would be sorted as Ep 1 > Ep 10-19 > Ep 100 > Ep 2 > Ep 20-29, and so on.

Suggestion would be to standardise the filenames depending on the total number of episodes of the series, and hence the episode filenames would, by default, be Ep 01, Ep 02, or, for series with >100 episodes, Ep 001, Ep 002, and so on, to better facilitate playing of the downloaded episodes on other devices / in-home players.

**Comment by lap00zza** [comment]
Thanks for this great suggestion.

**Comment by lap00zza** [comment]
This is addressed in rewrite/typescript branch. It will be published by the end of this month.

**Comment by Neptuneras** [comment]
Thank you so much.
