### ISSUE TITLE
i tried downloading a bunch of stuff and after like 2 series worth of downloads it stopped working, i uninstalled and reinstalled the companion and then restarted my computer with no luck

### ISSUE THREAD

**Issue by RavenKillz** [lap00zza/9anime-Companion#18]

**Comment by RavenKillz** [comment]
sorry ima noob on github

**Comment by lap00zza** [comment]
@RavenKillz hi. Sorry for the late reply. Can you please give me the following information?
* Which browser are you using the extension on (Chrome/Firefox)?
* Which version of the extension are you using (this can be found on the popup)?

**Comment by densityx** [comment]
@lap00zza I think it's better to limit the download to 4 or 5 episodes per batch, currently if there's 12 episode, It will download all in one.

**Comment by lap00zza** [comment]
Preliminary implementation of this is done with #27 . Please follow the conversation there.
