### ISSUE TITLE
Cant download cause its default server is F2.

### ISSUE THREAD

**Issue by Jonotaku** [lap00zza/9anime-Companion#21]
I cant download it because the rest of the episodes in 1080p stop at episode 12 (Trying to download Dragon ball super btw) Other then that everything else works fine. just wish it downloaded them all on the F1 server or if it cant find and more it should come up with an error or something to switch to the next server....
-_-

**Comment by lap00zza** [comment]
Hi. Thanks for using 9anime Companion 😄 . Automatic fallback is a planned feature. Thing is I am quite tied  up these days. So, this might take some time.

**Comment by lap00zza** [comment]
This is fixed in the rewrite version. Now a download_all button is attached to all 9anime Servers (F2, F4 etc). Support for downloading from RapidVideo will be added as well.
