### ISSUE TITLE
Suggestion : Enable download with IDM with Generate Link feature

### ISSUE THREAD

**Issue by garybempo** [lap00zza/9anime-Companion#23]
First of all thank you for creating the awesome extension for 9anime. Here is my suggestion to add to the extension.

Beside download the video with Chrome's default download manager, add another option to generate the video download link for users to download those videos with third party softwares like IDM (Internet Download Manager).

Like this:
![capture](https://cloud.githubusercontent.com/assets/25032545/26720422/cd3a5b2a-47ba-11e7-984a-1582a45516ce.PNG)

Then a box will pop out after users pressed the "Generate Link":
![capture2](https://cloud.githubusercontent.com/assets/25032545/26720432/d6e236ac-47ba-11e7-81df-44478d887f5a.PNG)

Hope this is easy implement and good suggestion to the extension. And sorry if this was suggested before.

*those pictures edited with Microsoft Paint only.

**Comment by lap00zza** [comment]
Preliminary implementation of this is done with #27 . Please follow the conversation there.
