### ISSUE TITLE
A couple suggestions you could possibly put in this awesome extension. 

### ISSUE THREAD

**Issue by Jonotaku** [lap00zza/9anime-Companion#25]
It would be nice if you could limit the downloads (Que them so when one finishes the next one will start) because about 10% of my videos fail on a huge download spree....
Also when they fail and you click resume. It renames the file to "videoplayback.mp4" I want it to be renamed the same as it was when it was downloading like "blah_blah_blah_E13(1080p)" You know what i mean right.
-Jono

**Comment by lap00zza** [comment]
Hi @Jonotaku . Thanks for the suggestion (and for using 9anime Companion 😄 ). However these days I am busy with a different project so I won't be able to work on this for a while. This one might take some time to implement.

Cheers
lap00zza

**Comment by lap00zza** [comment]
When the downloads fail, I don't have any way to rename them. Its done behind the scenes by chrome.
