### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by JoJoToast** [lap00zza/9anime-Companion#27]
After saying the usual http://prntscr.com/fjbamx it just doesn't download anything anymore, a few other people seem to have the same problem so it doesn't seem to just be me, I really love this extension and hope you can get it working again.

**Comment by lap00zza** [comment]
@JoJoToast hello. It looks like 9anime changed something on the site causing it to break the way 9anime Companion downloads. I am actually quite busy irl. I can only start working on the extension again from next month. Sorry for the delay and thanks for using 😄 .

**Comment by lap00zza** [comment]
@JoJoToast I will try to fix this download problem today or tomorrow, as I have some free time. Ping me on discord `Arsenic#1019`. If I am able to fix it, I will give you a link to the zip file.

**Comment by lap00zza** [comment]
These are the working versions with downloads fixed. Try it out and lemme know if there are any issues.
* https://www.dropbox.com/s/37t9m4stspqokyt/9anime_Companion_chrome.zip?dl=0
* https://www.dropbox.com/s/vvxwd4dar9qgm0k/9anime_Companion_firefox.zip?dl=0

Instructions for using them can be found here:
https://github.com/lap00zza/9anime-Companion/wiki/Running-in-Developement-Mode 
(*PS: skip the download part and follow the browser instructions*)

**Comment by JoJoToast** [comment]
Works fine for me now, thanks so much!

**Comment by lap00zza** [comment]
Fix for titles as per this [Reddit Thread](https://www.reddit.com/r/9anime/comments/6mla6k/when_batch_downloading_with_9anime_companion/)

* Chrome: https://www.dropbox.com/s/cj6ylucovcgx38b/9anime_Companion_chrome_title_fix.zip?dl=0
* Firefox: https://www.dropbox.com/s/239mjflvguvqnps/9anime_Companion_firefox_title_fix.zip?dl=0

If its not working for you, please post here.

**Comment by lap00zza** [comment]
Latest working version is linked in the comment above (https://github.com/lap00zza/9anime-Companion/issues/27#issuecomment-308515047)

**Comment by lap00zza** [comment]
I am closing this issue as all of the problem are resolved in the rewrite version. https://chrome.google.com/webstore/detail/9anime-companion/fopcehkidabibdmachbcpbgllhehknah
