### ISSUE TITLE
9anime Companion v1

### ISSUE THREAD

**Issue by densityx** [lap00zza/9anime-Companion#31]
Some of my suggestions for V1

- [ ] Show only limited number of *Recently Watched* list on popup
- [ ] Show only limited number of *Recently Pinned* list on popup
- [ ] Dedicated Pinned and Recently Watch list page
- [x] Auto Mal Sync
- [ ] Custom theme [custom styling & full theme]
- [x] New settings page [with more advance settings]
- [ ] Playback settings [eg 1 second backward on left arrow]
- [ ] Browser notification for Pinned anime?
- [ ] Highlight pinned anime on Anime Schedule Page
~~- [ ] Show **download** options depending on resolution [if max 720, 1080p button will be hidden]~~
- [ ] Playback speed as suggested here #20 

and that's all for now

**Comment by densityx** [comment]
Both if possible, being able to change specific element color and even change the entire theme (eg white theme)

**Comment by lap00zza** [comment]
> Show download options depending on resolution [if max 720, 1080p button will be hidden]

@densityx what happens when within the same anime, some episodes have lower quality videos and some higher quality? Check: https://github.com/lap00zza/Grabber/issues/13 for some context.

**Comment by densityx** [comment]
Ahhh... I understand what you are saying :frowning:

**Show download options depending on resolution [if max 720, 1080p button will be hidden]**
this is only applicable if the user is only downloading single episode

So I think using default fallback resolution (https://github.com/lap00zza/Grabber/issues/13) is good for this one

**Comment by lap00zza** [comment]
@densityx can you place all the suggestions in the Nice To Have column here: https://github.com/lap00zza/9anime-Companion/projects/2

Make sure to use a new card for each suggestion

**Comment by lap00zza** [comment]
Closing this issue. Moved the remaining tasks to the https://github.com/lap00zza/9anime-Companion/projects/2.
