### ISSUE TITLE
A little bit confused about the installation process and download all feature

### ISSUE THREAD

**Issue by TheMiziko** [lap00zza/9anime-Companion#34]
Hey ! Im sorry if it's a stupdi question, but I'm a little bit confused about the installation process, and what is needed for me for 9anime-Companion to work,

if someone could help me with what I need I would appreciate it :D 

and is download all safe to use ? in terms of how many request sit sends to the website ?

**Comment by lap00zza** [comment]
@TheMiziko yeah its safe. It sends a request every 2 seconds. Regarding the installation process, did you check this: https://github.com/lap00zza/9anime-Companion/issues/27#issuecomment-308515047

https://github.com/lap00zza/9anime-Companion/wiki/Running-in-Developement-Mode

Let me know if you need help in any specific step.

On a side note, if you use Discord, add me `Arsenic#1019`. I am online atm. Will help you out.

**Comment by TheMiziko** [comment]
After conversation on Discord, all issues were fully resolved ;). Thank you for helping
