### ISSUE TITLE
Change default download folder for anime downloads from the extension ?

### ISSUE THREAD

**Issue by TheMiziko** [lap00zza/9anime-Companion#36]
As in title is there, or will there be a way to change where all the anime are downloaded with "download all" feature ? :D

**Comment by lap00zza** [comment]
Hi. For downloads, there are 2 ways:
1. Show a `Save as` dialog to the user for each file
2. Automatically download and set the location.

For 2, there is no way to change the location (as far as I know). For example, say you default download location (as per your Chrome settings) is `D:\Downloads` and say you are downloading the anime `Gintama`, at best what can be done is change `D:\Downloads\9anime Companion\` to `D:\Downloads\Gintama` or something similar. Its not possible to say change it to `C:\Gintama`.

For 1, it is possible, but while downloading a lot of episodes (think 50+), you will end up with 50 `Save as` dialog boxes. And that wont be a pretty sight 😄 

Do let me know if my explanation was not clear.

**Comment by sgr1997** [comment]
when i try batch downloading it gives random names to episode..is there any way they can be downloaded having number of that episode

**Comment by lap00zza** [comment]
@sgr1997 I am guessing this happens when you use `external` method on episodes from RapidVideo. If that's the case, then use the `browser` method. IDM doesn't seem to recognize the episode metadata from the URL in case of RapidVideo links (which are direct links).

**Comment by lap00zza** [comment]
@densityx @WEBhicham can you look into https://github.com/lap00zza/9anime-Companion/issues/36#issuecomment-341404347
