### ISSUE TITLE
Error: Something went terribly wrong while fetching the download links. Please try again.

### ISSUE THREAD

**Issue by amitaffright** [lap00zza/9anime-Companion#37]
Just now i was trying to download (SHINGEKI NO KYOJIN SEASON 2 (DUB). I tried generating external links 
![screenshot 4](https://user-images.githubusercontent.com/29123717/28519639-05859a24-708a-11e7-8f59-6ed767e18a1b.png)
but i am getting (Error: Something went terribly wrong while fetching the download links. Please try again.) I am getting same error on other anime`s tooo ( I am using the latest version of the extension  "9anime_Companion_chrome_title_fix" which you`ve uploaded 13 days ago so can you please fix this issue. Thank You

**Comment by lap00zza** [comment]
Hi can you please try with this once

https://www.dropbox.com/s/37t9m4stspqokyt/9anime_Companion_chrome.zip?dl=0

If its not working, reply here.

**Comment by amitaffright** [comment]
Not working i tried generating link of episode 1 and  episode 2. I am not getting any error`s this time but fetched link Popup is empty ![screenshot 6](https://user-images.githubusercontent.com/29123717/28526555-80211c52-70a5-11e7-8b40-4f5336acef09.png) . But just now 9anime removed direct link to download 720p or 1080p so i guess its 9anime`s server side issue.

**Comment by amitaffright** [comment]
Extension you just gave me is working i guess cause extension is generating working 360p links. Thank you


> Hi can you please try with this oncehttps://www.dropbox.com/s/37t9m4stspqokyt/9anime_Companion_chrome.zip?dl=0If its not working, reply here.
> --

**Comment by lap00zza** [comment]
No probs. Some links keep going down occasionally. If this issue persists, do reply back. I will keep the issue open.

**Comment by amitaffright** [comment]
Hey 9anime just fixed 720p and 1080p links extension is working fine and generating links. But only problem i am facing right now is if you`ll try to download any episode with generated links it will show file not found (IDM) after comparing it with the direct link provided by 9anime generated link is missing ? after m37, after adding ? to m37 generated links works.
![screenshot 9](https://user-images.githubusercontent.com/29123717/28537440-7964d8a4-70c8-11e7-9da7-5de3dac1ed50.png)

**Comment by lap00zza** [comment]
Here are the fixed links
* Chrome: https://www.dropbox.com/s/37t9m4stspqokyt/9anime_Companion_chrome.zip?dl=0
* Firefox: https://www.dropbox.com/s/vvxwd4dar9qgm0k/9anime_Companion_firefox.zip?dl=0

Try them and let me know if you are able to download them correctly.

**Comment by amitaffright** [comment]
Links are working now, you can close this issue. Thank you for the fix.

> Here are the fixed links
> 
> Chrome: https://www.dropbox.com/s/37t9m4stspqokyt/9anime_Companion_chrome.zip?dl=0
> Firefox: https://www.dropbox.com/s/vvxwd4dar9qgm0k/9anime_Companion_firefox.zip?dl=0
> Try them and let me know if you are able to download them correctly.
