### ISSUE TITLE
Social link hide feature doesn't block them 

### ISSUE THREAD

**Issue by loupduqc** [lap00zza/9anime-Companion#4]
see image http://puu.sh/vg8U3/1c3f33f474.jpg

**Comment by loupduqc** [comment]
update for the other build http://puu.sh/vg8ZI/06275a94de.jpg

**Comment by lap00zza** [comment]
I am not able to reproduce this issue as of now. I will try this in other pc's. I have 1 question:
Are you using the dev build and the chrome web store version together? (I have a feeling its because of that)

**Comment by lap00zza** [comment]
This is closed on https://github.com/lap00zza/9anime-Companion/commit/08ad51f7c9cf47c34a2b2bcac4f10aa8d75af9c0.
