### ISSUE TITLE
Download function and adblocking

### ISSUE THREAD

**Issue by kaithar** [lap00zza/9anime-Companion#40]
I've noticed something odd, it seems that if I have `20a840a14a0ef7d6.com` adblocked then the chrome extension doesn't work properly.  Any ideas?  It's a really nasty popup site, so I'd rather not have it able to load.

**Comment by lap00zza** [comment]
@kaithar hi can you tell me which version of 9ac are you using? 

Is it the normal one or the one from `rewrite/typescript`

**Comment by kaithar** [comment]
It's the one linked to in #27 so probably the normal one

**Comment by lap00zza** [comment]
I will find out what wrong with that one and update you here.

In the meantime, if you want you can try this version: https://github.com/lap00zza/9anime-Companion/tree/rewrite/typescript

download link: https://ci.appveyor.com/project/lap00zza/9anime-Companion/build/artifacts?branch=rewrite%2Ftypescript

This version has everything the old version had minus the `pinned anime list` and a really good adblocker (blocks 100% ads/popups without any other blockers enabled)

**Comment by lap00zza** [comment]
@kaithar I checked it out. Looks to be working fine in my browser. So I can't say for certain whats wrong.
![](https://image.ibb.co/mA1Fzv/ss.png)

![](https://image.ibb.co/byg16a/ss1.png)

**Comment by kaithar** [comment]
That's weird, the quality drop down and download buttons were disabled for me... solved it by grabbing the latest ublock origin 👍

**Comment by lap00zza** [comment]
Glad that its working now. Since this is solved, I am closing this issue. If you get the same problem again, reopen this issue.
