### ISSUE TITLE
Suggestion: Keyboard Shortcut and Features Improvement

### ISSUE THREAD

**Issue by densityx** [lap00zza/9anime-Companion#43]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your suggestion:**
- [x] <kbd>t</kbd> shortcut should scroll to the top of the page instead only on top of the player
~~- [ ] <kbd>ss</kbd> for Screen Shot or <kbd>c</kbd> Capture should be used for the screenshot feature~~
- [ ] <kbd>a</kbd> shortcut should be used in the settings page to show all available settings **shortcut**
- [x] when scrolling top, it should use **smooth animation** cuz me ❤️ it

that's all for now

**Comment by densityx** [comment]
@lap00zza can we have this soon?

**Comment by lap00zza** [comment]
Screenshot is on hold. Other 1, 3 & 4 will be done soon 😄

**Comment by lap00zza** [comment]
1 & 4 is done. Screenshot wont be added anytime soon due to issues with canvas and having to support multiple players. 3 won't be needed because there is a dedicated button in the settings page dedicated to shortcut

 ![Screenshot](http://i.imgur.com/SrYkJg9.png)
