### ISSUE TITLE
Enable or Disable Adblock on new Install

### ISSUE THREAD

**Issue by densityx** [lap00zza/9anime-Companion#51]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
I am suggesting that on every new install, we should ask user to either enable or disable their adBlock especially for 9anime sites. Why? it's because **9anime Companion** come with default adblock and this will allow the extension to automatically make use of the ads blocking mechanism / settings.

**Comment by lap00zza** [comment]
Added in 72fb32a4a8343644976ced0f35c4351c7ae0577f
