### ISSUE TITLE
Allow User to Pick Download Location

### ISSUE THREAD

**Issue by Looseminded** [lap00zza/9anime-Companion#52]
- [x] Suggestion

When using the download all feature, downloading files defaults to the downloads section of the primary drive (in this case on Windows, C:\).  Would it be possible in future builds to allow the user to select where they would like to download the files to?  (e.g. C:\ is running out of space, I'd rather store my downloads at, say, I:\Anime\New_Downloads\)

I wouldn't rate this up high on the list but if it's possible I'd like to see this in a future build.  Thanks for all the work you do!

**Comment by lap00zza** [comment]
Hello @Looseminded . Thanks for the suggestion. There are 2 ways for a extension to download files:

1. Show a `Save as` dialog to the user for **each** file
2. Automatically download and set the location.

For 2, there is no way to change the location completely. For example, say your default download location (as per your Chrome settings) is `D:\Downloads` and say you are downloading the anime `Gintama`, at best what can be done is change `D:\Downloads\9anime Companion\` to `D:\Downloads\Gintama` or something similar. Its not possible to say change it to `C:\Gintama`.

For 1, it is possible, but while downloading a lot of episodes (think 50+), you will end up with 50 `Save as` dialog boxes. 

There is a feature request for this in the chromium forums: https://bugs.chromium.org/p/chromium/issues/detail?id=290562

**Comment by Looseminded** [comment]
Fair enough, thanks for the quick response @lap00zza
