### ISSUE TITLE
Suggestion: Add a link to MAL pages that directs to the show on 9anime

### ISSUE THREAD

**Issue by Rakqoi** [lap00zza/9anime-Companion#65]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

If it's not outside the scope of the extension (since it would modify an entirely different website), it would be very convenient to have a button on MyAnimeList which directs to that show on 9anime, or to a search page using the anime's title as the query. 

Here's a mockup image I did with the Chrome element editor:

![tbxuwue](https://user-images.githubusercontent.com/31815644/30247057-af79a1ce-95d8-11e7-84a5-ce0653500dc3.png)

**Comment by lap00zza** [comment]
@Rakqoi thanks for the suggestion. Do keep an eye on this thread for updates.

**Comment by Waterflash** [comment]
kitsu.io integration?
