### ISSUE TITLE
Custom download map

### ISSUE THREAD

**Issue by Wprokiller** [lap00zza/9anime-Companion#73]
make an option to choose where your standard download direction is going to be.

**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Make it possible to decide for yourself where the download direction is gonna be in the settings of 9anime companion. because I've got my desktop on my SSD and prefer to have it downloaded at my other driver. now I am changing the direction every download. and that is annoying and takes me a lot of time

**Comment by lap00zza** [comment]
Hi @Wprokiller please check these 2 links for the reason as to why this is not possible.

* https://github.com/lap00zza/9anime-Companion/issues/52#issuecomment-326259523
* https://github.com/lap00zza/9anime-Companion/issues/36#issuecomment-317237165

If you have any more questions lemme know.
