### ISSUE TITLE
Issues with download

### ISSUE THREAD

**Issue by TheMiziko** [lap00zza/9anime-Companion#80]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Sometimes, when downloading episode I get server error
https://gyazo.com/4cc9ea89ee3e71783cdd4d17318bdb45
Any way to prevent it or fix it ? is it normal ?

**Comment by lap00zza** [comment]
@TheMiziko that issue cant be solved sadly (or atleast I don't know of a fix). The only "fix" would be to increase the interval at which the automated download occurs (it is 2 seconds now) but even then its not guaranteed to fix it. Does this happen very frequently?

**Comment by TheMiziko** [comment]
@lap00zza On every download. Each 3-4 episodes

**Comment by lap00zza** [comment]
You can't directly. Its set here: https://github.com/lap00zza/9anime-Companion/blob/cee4b2fddf30c98b236b988da10017e6eba60cd7/src/lib/download_all/core.ts#L164

If you really want to change the interval yourself you will need to clone this repo, edit that line and build the extension (https://github.com/lap00zza/9anime-Companion/wiki/Build-Instructions).

**Comment by TheMiziko** [comment]
@lap00zza Just to clarify, in the programs needed to install this version I need this programs ?
: https://desktop.github.com/
https://nodejs.org/en/

**Comment by lap00zza** [comment]
Node: https://nodejs.org/en/download/current/
Git: https://git-scm.com/download/win

Do try out the 5second interval version I uploaded. Because even after you download node and git, the dependencies for 9nime Companion is somewhat large.

**Comment by TheMiziko** [comment]
@lap00zza Unfortunately, it made it even worst :D https://gyazo.com/26e9472bcbe59ca11d9eb660850bdad2

now every second download has server problem error

**Comment by lap00zza** [comment]
#rip. I dunno what to say 😄 

I will keep this thread open just in case someone else have an idea on how to fix this issue.

**Comment by TheMiziko** [comment]
@lap00zza Just another screenshot from download : https://gyazo.com/4165235e6f6d9346fddee5869b1097ba

Just in case, I tried incognito mode to exvlude all other extensions I use, different anime(obviously) and different servers + qualities.

All have this same problem

**Comment by deathsec** [comment]
@TheMiziko you could check this out https://github.com/deathsec/9anime , its in alpha release but still does the job well. I hope it helps!

**Comment by lap00zza** [comment]
@deathsec you have a nice project, but this is not the place to promote it. All further unrelated comments will be deleted.

**Comment by deathsec** [comment]
@lap00zza just helping the folks out , they should have other options too. Because I had the same problem.

**Comment by lap00zza** [comment]
Send me a PR for the readme with your projects link and name. That would be better 😄 .

```
### Other interesting projects
YOUR PROJECT NAME + URL - DESCRIPTION
```
@deathsec
