### ISSUE TITLE
Function to not update to MAL if your watchcount on MAL is higher than the episode you're on

### ISSUE THREAD

**Issue by SimonMattila** [lap00zza/9anime-Companion#84]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

A helpful feature I think would be if you could toggle wether or nor it should automatically update episodes to MyAnimeList or not if the episode you are on is lower than the episode you have on MyAnimeList.

So let's say I'm on episode 5 and MAL has that I'm on episode 10, then it wouldnt update until I'm at episode 11. 

Sometimes I like to go back to older episodes for certains scenes but have to reupdate back again.

Thanks

**Comment by lap00zza** [comment]
Shipped in version 1.2.0.
