### ISSUE TITLE
Ads at homepage,when remove ads button are on

### ISSUE THREAD

**Issue by sliperhr** [lap00zza/9anime-Companion#86]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Hey lap00zza,im loving your 9anime companion,but i still got ads at the homepage (see picture below) , when i try using other pc/laptop,there are no ads,how can this happen?
![untitled](https://user-images.githubusercontent.com/33209981/32151923-9af55aea-bd5b-11e7-8a99-c3cd12310893.jpg)

**Comment by CyferShepard** [comment]
Refer to problem #85 . I found a new ad source you can try adding to your filter list or wait till the new update rolls out.

**Comment by CyferShepard** [comment]
Tray adding this "^https?:\\/\\/([a-z0-9]+[.])*bebi\\.com".

**Comment by lap00zza** [comment]
Hi @sliperhr , as @CyferShepard mentioned you can add this line `^https?:\/\/([a-z0-9]+[.])*bebi\.com` to the filter list. Here is a gif demonstrating how to do it: ![](https://i.imgur.com/PZZyaJC.gif)

On the next update it will be there as a default filter.

**Comment by densityx** [comment]
@sliperhr rest assured, we got this under control

**Comment by lap00zza** [comment]
Fixed and shipped in version 1.2.0.
