### ISSUE TITLE
Outdated version number on settings screen

### ISSUE THREAD

**Issue by SimonMattila** [lap00zza/9anime-Companion#96]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [ ] Suggestion
- [x] Other (please describe):

**Describe your issue:**
Good job with the 1.3.0, noticed however that you missed to change the version number on the settings page aswell, perhaps make it automatically link to the latest version tag from GitHub?
[Screenshot](http://prntscr.com/hd486r)

**Comment by lap00zza** [comment]
Oh rip. I completely forgot about that. I should really make a script to do it automatically.
