### ISSUE TITLE
Ad block no longer working

### ISSUE THREAD

**Issue by SheepKid12** [lap00zza/9anime-Companion#97]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
When using the ad blocking feature of this extension, i get a message saying that I need to disable ad blocking, but I don't want to if I don't have to.

https://imgur.com/a/3Z4IN link to the message I am talking about.

**Comment by SimonMattila** [comment]
I got the same problem, I think it has to do with the 1.3.0 additions to adblocking. Using strictly uBlock Origin to block the ads doesn't trigger the anti-adblock from 9a-s side

**Comment by lap00zza** [comment]
oh wow. Thanks for the report. I will try to find out whats up.

**Comment by lap00zza** [comment]
@SimonMattila @SheepKid12 did this start today or 2-3 days back? Also for some reason I seem to be getting that message with uBlock Origin on (and 9anime Companion remove ads off)

**Comment by lap00zza** [comment]
Tested version 1.2.0, results are the same. The only way to **remove the disable adblock warning** is to completely **disable 9anime Companion** and then using ad blocker of your choice. Can anyone please confirm this? Previous versions of the extension can be found here: https://github.com/lap00zza/9anime-Companion/releases

**Comment by mrGRINCH** [comment]
I'm getting the same "Please disable AdBlock then refresh this page and try again." error message.
I have tried disabling "remove ads" in 9AC with ublock running but still receive the error message.
I have tried disabling ublock with 9AC running with "remove ads" enabled and still receive the message.
 have tried disabling ublock with 9AC unning with "remove ads" disabled and videos will play.
I have tried disabling both ublock and 9AC completely and videos will play.

Hope this helps.

**Comment by densityx** [comment]
Here's how it work,

I have tested it on 9AnimeCompanion v1.1, v1.3 and uBlock Origin

If you have any of those extension on, once you load the video page and it's still loading... pressing the play button will enable you to play the video and you won't see the "Please disable AdBlock then refresh this page and try again." message

But then if you have any of those extension on and you wait the video page to load until it finishes, when you press the play button, you will see the "Please disable AdBlock then refresh this page and try again."

I assume 9anime detect this until the page is fully loaded

**Comment by lap00zza** [comment]
Please try the builds here and let me know if the adblock message still shows up: https://ci.appveyor.com/project/lap00zza/9anime-companion/branch/master/artifacts

How to install: https://github.com/lap00zza/9anime-Companion/wiki/Running-in-Developement-Mode

**Comment by mrGRINCH** [comment]
Working in Firefox Quantum 57.

There is an ad still showing in the video player though.
![untitled](https://user-images.githubusercontent.com/6090377/33118625-7bfdb48a-cfc0-11e7-8bdd-8b41b8dbd559.png)

**Comment by Wyn10** [comment]
Build worked for me in Waterfox 55.2.2 with Ublock Origin enabled.

**Comment by lap00zza** [comment]
@Wyn10 please try once with 9ac remove ads on and Ublock Origin disabled and see if the ads are still there.

**Comment by lap00zza** [comment]
Once build `1.4.0.6` is fully tested, I will release an emergency fix to Chrome Web Store and Addons.Mozilla.Org.

**Comment by mrGRINCH** [comment]
Version 1.4.0.6 tested and working perfectly.

**Comment by deathsec** [comment]
well they seem to put up some fight , this is the reason why you are getting those errors https://www.reddit.com/r/9anime/comments/7el3p7/9anime_changes_adblock_blocker_banner_ads_etc/ , and I think are changing the adblock killer everyday...

**Comment by lap00zza** [comment]
Saw that post. It takes quite a bit of effort to find a way to disable the anti adblocker. If they do it everyday it will be really hard for me to keep up.

**Comment by deathsec** [comment]
but a small trick helped me you could try that in your javascript , the trick is:
* Use UBlock Origin ( **That kills all ads from 9anime** ) or any other adblocker in general ( yours)
* The Ad Killer is in the autoplay feature , you just need to rebuild that autoplay
* I created a small script to open the next episode url for autoplay

# Manually 
You just need to copy the next episode url and then paste it in the address bar and press enter.
Simple , right.. ?

**Comment by deathsec** [comment]
hope this helps!

**Comment by lap00zza** [comment]
Yup that works. That was the first thing I tried today. I was planning to stick with that at first, but I really wanted to find out what the detection was 😄 (personal curiosity). If they every change it again I will just do what you mentioned.

**Comment by lap00zza** [comment]
Added the following banner on the settings page which will be removed in the next update.
![image](https://user-images.githubusercontent.com/8621583/33123131-52220204-cf9f-11e7-9415-ae743175c1f2.png)

**Comment by lap00zza** [comment]
This issue is fixed in release 1.3.1 (https://github.com/lap00zza/9anime-Companion/releases/tag/1.3.1). Changes will be made available in Chrome Web Store and Addons.Mozilla.Org in 1 hour.

**Comment by lap00zza** [comment]
Changes are live. Please update to `1.3.1`.
