### ISSUE TITLE
Plugin wont run at all with the 9anime updates to the website

### ISSUE THREAD

**Issue by KingFishy492** [lap00zza/9anime-Companion#98]
- [x] Bug

**Describe your issue:**
So it seems that 9anime have changed how they have things running witch is great for getting things back in track but bad for people that don't like ads and like this plugin it seems they class the hole thing as an ad blocker and have just out right blocked it so even if you are to turn off the part of the extension of this it will still say you have it turned on and will not play anything unless you uninstall the extension #97 this is what they have said but its a bit more detailed on the info side of things and how far it goes hope it helps

**Comment by lap00zza** [comment]
its fixed now. I will publish the changes in 1 hour. This is the final release build: https://ci.appveyor.com/project/lap00zza/9anime-companion/build/1.4.0.7/artifacts
